logic:
  database:
    path: mishmash.db
    create_tables_if_nonexistent: True
  navigation:
    list_slice_size: 5
  mpd:
    host: localhost
    port: 6600
    socket: /var/run/mpd/socket

synchronisation:
  remote_music_collection:
    smb_host: 192.168.0.100
    local_mount_point: /media/ServerHDD
    remote_share_point_name: Multimedia
    location_relative_to_share_point: Music
    location_absolute: /mnt/HDD/share/Multimedia/Music

  local_music_collection:
    location: /home/pi/Music

log:
  path: krv2/log